version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb_spring
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: reservation-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb_spring?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      BEZKODER_APP_JWTSECRET: ea57eb7bee56775e6d33631b5b9ce4305bd014aae96d473e98ee6d99cc31f5b04d3855e257da480ae42f9becaf8f7aec3760eaab167da4938cdad140e5f850ab
      BEZKODER_APP_JWTEXPIRATIONMS: 86400000

  frontend:
    image: nginx:alpine
    container_name: reservation-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mysql-data: