spring.datasource.url=jdbc:mysql://localhost:3307/testdb_spring?useSSL=false
spring.datasource.username=root
spring.datasource.password=
server.port=8083
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
bezkoder.app.jwtSecret= ea57eb7bee56775e6d33631b5b9ce4305bd014aae96d473e98ee6d99cc31f5b04d3855e257da480ae42f9becaf8f7aec3760eaab167da4938cdad140e5f850ab
bezkoder.app.jwtExpirationMs=86400000

spring.application.name=auth-service
#eureka.client.service-url.defaultZone=http://localhost:8791/eureka/